### ISSUE TITLE
Audio section isn't rendered always

### ISSUE THREAD

**Issue by vikrant-pune** [piyush-eon/react-dictionary-wordhunt#1]
Hi ,
For few words we do see audio rendered for for most we don't see it getting rendered 

Could you let me know how to debug this 

![image](https://user-images.githubusercontent.com/5338620/132172788-c3d66b45-6277-444c-a5ba-bb2c192141df.png)

**Comment by piyush-eon** [comment]
Hello,
Its due to API, It doesn't have audio element for few of them
